apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-api
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      containers:
        - name: platform-api
          image: ghyro/platform:3.0.0
          env:
           - name: SQL_CONNECTION_STR
             value: "Server=tcp:platform-ms-sql,1433;Initial Catalog=PlatformManager;Persist Security Info=False;User ID=SA;Password=Test-12345;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
           - name: ASPNETCORE_ENVIRONMENT
             value: "Development"
          ports:
            - name: platform-api-p
              containerPort: 8080
