apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-api
  template:
    metadata:
      labels:
        app: platform-api
    spec:
      containers:
        - name: platformservice
          image: ghyro/platform:latest
          env:
           - name: SQL_CONNECTION
             value: "Server=tcp:mssql-clusterip-srv,1433;Initial Catalog=PlatformDb;Persist Security Info=False;User ID=SA;Password=Test-12345;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
           - name: COMMAND_API
             value: "http://command-clusterip-srv:80/api/c/Platform"
---
apiVersion: v1
kind: Service
metadata:
  name: platform-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platform-api
  ports:
  - name: platform-api
    protocol: TCP
    port: 80
    targetPort: 80
